[package]
name = "assumevalid"
version = "0.1.0"
edition = "2024_07"

[executable]
allow-syscalls = true

[dependencies]
cairo_execute = "2.11.4"
consensus = { path = "../consensus" }
utils = { path = "../utils" }
stwo_cairo_air = { path = "../../../stwo-cairo/stwo_cairo_verifier/crates/cairo_air", features = [
    "qm31_opcode",
] }

[features]
default = ["syscalls"]
syscalls = ["consensus/syscalls", "utils/syscalls"]
blake2b = ["consensus/blake2b"]
blake2b_mock = ["consensus/blake2b_mock"]

[dev-dependencies]
cairo_test.workspace = true

[scripts]
test = "scarb cairo-test && scarb --profile release build --target-kinds executable && ../../scripts/data/integration_tests.sh"
