[package]
name = "assumevalid"
version = "0.1.0"
edition = "2024_07"

[executable]
allow-syscalls = true

[dependencies]
cairo_execute = "2.11.4"
consensus = { path = "../consensus" }
utils = { path = "../utils" }
stwo_cairo_air = { git = "https://github.com/starkware-libs/stwo-cairo", rev = "a8a434b521a588cf80eb3625affb984f9913be6c", features = ["qm31_opcode"] }

[features]
default = ["syscalls"]
syscalls = ["consensus/syscalls", "utils/syscalls"]

[dev-dependencies]
cairo_test.workspace = true

[scripts]
test = "scarb cairo-test && scarb --profile release build --target-kinds executable && ../../scripts/data/integration_tests.sh"
