[package]
name = "client"
version = "0.1.0"
edition = "2024_07"

[executable]
allow-syscalls = true

[lib]

[dependencies]
cairo_execute = "2.11.4"
consensus = { path = "../consensus" }

[dev-dependencies]
cairo_test.workspace = true

[scripts]
test = "scarb --profile release build && ../../scripts/data/integration_tests.sh"
regenerate_tests = "../../scripts/data/regenerate_tests.sh"

[features]
default = ["syscalls"]
syscalls = ["consensus/syscalls"]
blake2b = ["consensus/blake2b"]
blake2b_mock = ["consensus/blake2b_mock"]
