[workspace]
members = ["packages/*"]

[workspace.package]
description = "Bitcoin ZK client."
cairo-version = "2.12.2"
version = "0.1.0"
readme = "README.md"
repository = "https://github.com/keep-starknet-strange/raito"
license-file = "LICENSE"

[workspace.dependencies]
cairo_test = "2.12.2"

[cairo]
enable-gas = false

[profile.proving]
inherits = "release"

[profile.proving.cairo]
enable-gas = false
sierra-replace-ids = true
# NOTE: this flag set causes build errors in Cairo 2.12.0 (because of use of print right before a panic).
# Use only for assumevalid package.
# unsafe-panic = true

[profile.release.cairo]
enable-gas = false
